<?php

use App\Models\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $departments = [
            ['id' => 1, 'name' => 'Management Administration', 'process_id' => '001'],
            ['id' => 2, 'name' => 'President', 'process_id' => '002'],
            ['id' => 3, 'name' => 'Strategy & Operation', 'process_id' => '003'],
            ['id' => 4, 'name' => 'RICA', 'process_id' => '004'],
            ['id' => 5, 'name' => 'Legal & Prvilege', 'process_id' => '005'],
            ['id' => 6, 'name' => 'Information Technology', 'process_id' => '006'],
            ['id' => 7, 'name' => 'Operation', 'process_id' => '007'],
            ['id' => 8, 'name' => 'ADM Management', 'process_id' => '008'],
            ['id' => 9, 'name' => 'Human Resource & General Admin', 'process_id' => '009'],
            ['id' => 10, 'name' => 'Human Resource', 'process_id' => '010'],
            ['id' => 11, 'name' => 'General Admin', 'process_id' => '011'],
            ['id' => 12, 'name' => 'SHE & ISO', 'process_id' => '012'],
            ['id' => 13, 'name' => 'Finance & Accounting', 'process_id' => '013'],
            ['id' => 14, 'name' => 'Finance Planning & Analysis', 'process_id' => '014'],
            ['id' => 15, 'name' => 'Accounting', 'process_id' => '015'],
            ['id' => 16, 'name' => 'A/R & Credit Management', 'process_id' => '016'],
            ['id' => 17, 'name' => 'Cash Management', 'process_id' => '017'],
            ['id' => 18, 'name' => 'Costing', 'process_id' => '018'],
            ['id' => 19, 'name' => 'Marketing', 'process_id' => '019'],
            ['id' => 20, 'name' => 'RF Sales', 'process_id' => '020'],
            ['id' => 21, 'name' => 'AC Sales', 'process_id' => '021'],
            ['id' => 22, 'name' => 'Order Coordinator', 'process_id' => '022'],
            ['id' => 23, 'name' => 'Customer Service', 'process_id' => '023'],
            ['id' => 24, 'name' => 'Supply Chain Management', 'process_id' => '024'],
            ['id' => 25, 'name' => 'Vendor Management & Sourcing', 'process_id' => '025'],
            ['id' => 26, 'name' => 'Cost Management', 'process_id' => '026'],
            ['id' => 27, 'name' => 'Import & Export', 'process_id' => '027'],
            ['id' => 28, 'name' => 'Order Management', 'process_id' => '028'],
            ['id' => 29, 'name' => 'Indirect Procurement', 'process_id' => '029'],
            ['id' => 30, 'name' => 'Utility', 'process_id' => '030'],
            ['id' => 31, 'name' => 'Indirect Production', 'process_id' => '031'],
            ['id' => 32, 'name' => 'Support Platform RF', 'process_id' => null],
            ['id' => 33, 'name' => 'Admin Support Platform RF', 'process_id' => '033'],
            ['id' => 34, 'name' => 'In House Part Production', 'process_id' => '233'],
            ['id' => 35, 'name' => 'Door Liner Forming (TF)', 'process_id' => '035'],
            ['id' => 36, 'name' => 'Inner box Forming (TF)', 'process_id' => '036'],
            ['id' => 37, 'name' => 'Metal Coat (MC)', 'process_id' => '037'],
            ['id' => 38, 'name' => 'Door bending & Glass ass`y A', 'process_id' => '039'],
            ['id' => 39, 'name' => 'Door forming A', 'process_id' => '040'],
            ['id' => 40, 'name' => 'RF Production  Line A', 'process_id' => '041'],
            ['id' => 41, 'name' => 'Inner Box A', 'process_id' => '042'],
            ['id' => 42, 'name' => 'Roll former A', 'process_id' => '043'],
            ['id' => 43, 'name' => 'Cab pre-assy A', 'process_id' => '044'],
            ['id' => 44, 'name' => 'Cabinet PU Foam A', 'process_id' => '045'],
            ['id' => 45, 'name' => 'Assembly A', 'process_id' => '046'],
            ['id' => 46, 'name' => 'System ass`y A', 'process_id' => '047'],
            ['id' => 47, 'name' => 'Vacuum A', 'process_id' => '048'],
            ['id' => 48, 'name' => 'Final & Packing A', 'process_id' => '049'],
            ['id' => 49, 'name' => 'Packing A', 'process_id' => '050'],
            ['id' => 50, 'name' => 'MIZ & Costing A', 'process_id' => null],
            ['id' => 51, 'name' => 'RF Production B Line', 'process_id' => '052'],
            ['id' => 52, 'name' => 'Inner Box B', 'process_id' => '053'],
            ['id' => 53, 'name' => 'Roll former B', 'process_id' => '054'],
            ['id' => 54, 'name' => 'Cab pre-assy B', 'process_id' => '055'],
            ['id' => 55, 'name' => 'Cabinet PU Foam B', 'process_id' => '056'],
            ['id' => 56, 'name' => 'Assembly B', 'process_id' => '057'],
            ['id' => 57, 'name' => 'System ass`y B', 'process_id' => '058'],
            ['id' => 58, 'name' => 'Vacuum B', 'process_id' => '059'],
            ['id' => 59, 'name' => 'Final  & Packing B', 'process_id' => '060'],
            ['id' => 60, 'name' => 'Packing B', 'process_id' => '061'],
            ['id' => 61, 'name' => 'MIZ & Costing B', 'process_id' => '062'],
            ['id' => 62, 'name' => 'Spare - B', 'process_id' => '063'],
            ['id' => 63, 'name' => 'Production Support RF', 'process_id' => '232'],
            ['id' => 64, 'name' => 'Admin -Production Support RF', 'process_id' => '070'],
            ['id' => 65, 'name' => 'RM Warehouse (RF)', 'process_id' => '071'],
            ['id' => 66, 'name' => 'FG Warehouse (RF)', 'process_id' => '072'],
            ['id' => 67, 'name' => 'Spare Part Warehouse (RF)', 'process_id' => '073'],
            ['id' => 68, 'name' => 'Quality AC', 'process_id' => '096'],
            ['id' => 69, 'name' => 'AC PQC', 'process_id' => '097'],
            ['id' => 70, 'name' => 'IQC (SAC)', 'process_id' => '098'],
            ['id' => 71, 'name' => 'OQC (SAC)', 'process_id' => '099'],
            ['id' => 72, 'name' => 'AC- R&D', 'process_id' => '104'],
            ['id' => 73, 'name' => 'AC R&D', 'process_id' => '105'],
            ['id' => 74, 'name' => 'Bom AC', 'process_id' => '106'],
            ['id' => 75, 'name' => 'AC- E&M', 'process_id' => '107'],
            ['id' => 77, 'name' => 'Spare - A', 'process_id' => '109'],
            ['id' => 79, 'name' => 'Spare - ', 'process_id' => '111'],
            ['id' => 80, 'name' => 'Spare - AC-IDU', 'process_id' => '113'],
            ['id' => 81, 'name' => 'Spare - RAC-ODU', 'process_id' => '114'],
            ['id' => 82, 'name' => 'Spare - CAC-ODU', 'process_id' => '115'],
            ['id' => 83, 'name' => 'Spare - WAC', 'process_id' => '116'],
            ['id' => 84, 'name' => 'RF Procurement', 'process_id' => '118'],
            ['id' => 85, 'name' => 'Subcontractor ', 'process_id' => '120'],
            ['id' => 86, 'name' => 'FUL FILL', 'process_id' => '121'],
            ['id' => 87, 'name' => 'HR-GET', 'process_id' => '123'],
            ['id' => 88, 'name' => 'Door bending B', 'process_id' => '124'],
            ['id' => 89, 'name' => 'Door forming B', 'process_id' => '125'],
            ['id' => 90, 'name' => 'Corprate Culture', 'process_id' => null],
            ['id' => 91, 'name' => 'Direct Production', 'process_id' => '145'],
            ['id' => 92, 'name' => 'RF Haier', 'process_id' => '146'],
            ['id' => 93, 'name' => 'PQC(RF) A', 'process_id' => '147'],
            ['id' => 94, 'name' => 'Production Planning A', 'process_id' => '148'],
            ['id' => 95, 'name' => 'Maintenance A', 'process_id' => '149'],
            ['id' => 96, 'name' => 'R&D /ET A', 'process_id' => '150'],
            ['id' => 97, 'name' => 'Production Platform  RF', 'process_id' => '151'],
            ['id' => 98, 'name' => 'Maintenance IH', 'process_id' => '152'],
            ['id' => 99, 'name' => 'Machine Engineering IH', 'process_id' => '153'],
            ['id' => 100, 'name' => 'PQC IH', 'process_id' => '154'],
            ['id' => 101, 'name' => 'R&D/ET IH', 'process_id' => '155'],
            ['id' => 102, 'name' => 'RF AQUA', 'process_id' => '156'],
            ['id' => 103, 'name' => 'PQC (RF) B', 'process_id' => '157'],
            ['id' => 104, 'name' => 'Production Planning B', 'process_id' => '158'],
            ['id' => 105, 'name' => 'Maintenance B', 'process_id' => '159'],
            ['id' => 106, 'name' => 'R&D /ET B', 'process_id' => '160'],
            ['id' => 107, 'name' => 'Technical Platform', 'process_id' => null],
            ['id' => 108, 'name' => 'RF E&M ', 'process_id' => '162'],
            ['id' => 109, 'name' => 'Admin E&M', 'process_id' => '163'],
            ['id' => 110, 'name' => 'Mechanical Engineering', 'process_id' => null],
            ['id' => 111, 'name' => 'Preventive Maintenance', 'process_id' => '165'],
            ['id' => 112, 'name' => 'Store', 'process_id' => '166'],
            ['id' => 113, 'name' => 'RF R&D', 'process_id' => '167'],
            ['id' => 114, 'name' => 'Admin R&D', 'process_id' => '168'],
            ['id' => 115, 'name' => 'BOM RF', 'process_id' => '169'],
            ['id' => 116, 'name' => 'Product Development RF', 'process_id' => '170'],
            ['id' => 117, 'name' => 'RF Quality', 'process_id' => '171'],
            ['id' => 118, 'name' => 'IQC (RF)', 'process_id' => '172'],
            ['id' => 119, 'name' => 'OQC (RF)', 'process_id' => '173'],
            ['id' => 120, 'name' => 'Repainting RF', 'process_id' => '174'],
            ['id' => 121, 'name' => 'Support Platform AC', 'process_id' => '175'],
            ['id' => 122, 'name' => 'ADM- Support Platform AC', 'process_id' => '176'],
            ['id' => 123, 'name' => 'SAC Micro', 'process_id' => null],
            ['id' => 124, 'name' => 'ADM SAC', 'process_id' => '178'],
            ['id' => 125, 'name' => 'Production Line SAC', 'process_id' => null],
            ['id' => 126, 'name' => 'Indoor 1', 'process_id' => '180'],
            ['id' => 127, 'name' => 'Indoor 2', 'process_id' => '181'],
            ['id' => 128, 'name' => 'Outdoor', 'process_id' => '182'],
            ['id' => 129, 'name' => 'PQC SAC', 'process_id' => null],
            ['id' => 130, 'name' => 'PQC (SAC)-Indoor 1', 'process_id' => '184'],
            ['id' => 131, 'name' => 'PQC (SAC)-Indoor 2', 'process_id' => '185'],
            ['id' => 132, 'name' => 'PQC (SAC)-Outdoor', 'process_id' => '186'],
            ['id' => 133, 'name' => 'Production Planning SAC', 'process_id' => '187'],
            ['id' => 134, 'name' => 'Production Platform AC', 'process_id' => '188'],
            ['id' => 135, 'name' => 'Production Support AC', 'process_id' => null],
            ['id' => 136, 'name' => 'FG Warehouse (SAC)', 'process_id' => '190'],
            ['id' => 137, 'name' => 'RM Warehouse (SAC)', 'process_id' => '191'],
            ['id' => 138, 'name' => 'AC Purchasing', 'process_id' => '192'],
            ['id' => 139, 'name' => 'WAC Micro', 'process_id' => null],
            ['id' => 140, 'name' => 'Admin-WAC', 'process_id' => '194'],
            ['id' => 141, 'name' => 'EVAP & Condenser Line  WAC', 'process_id' => '195'],
            ['id' => 142, 'name' => 'Production Line WAC', 'process_id' => null],
            ['id' => 143, 'name' => 'PQC  WAC', 'process_id' => '197'],
            ['id' => 144, 'name' => 'Production Planning WAC', 'process_id' => '198'],
            ['id' => 145, 'name' => 'Technical Platform AC', 'process_id' => '199'],
            ['id' => 146, 'name' => 'IQC (WAC)', 'process_id' => '200'],
            ['id' => 147, 'name' => 'OQC (WAC)', 'process_id' => '201'],
            ['id' => 148, 'name' => 'Spare - Door', 'process_id' => '202'],
            ['id' => 149, 'name' => 'AC', 'process_id' => '203'],
            ['id' => 150, 'name' => 'RF Purchasing', 'process_id' => '204'],
            ['id' => 151, 'name' => 'Inner Box B (VZ)', 'process_id' => '205'],
            ['id' => 152, 'name' => 'CAC', 'process_id' => '206'],
            ['id' => 153, 'name' => 'Spare Inner Box A', 'process_id' => '207'],
            ['id' => 154, 'name' => 'Spare Roll A', 'process_id' => '208'],
            ['id' => 155, 'name' => 'Spare Cab pre-assy A', 'process_id' => '209'],
            ['id' => 156, 'name' => 'Spare PU Foam A', 'process_id' => '210'],
            ['id' => 157, 'name' => 'Spare Assembly A', 'process_id' => '211'],
            ['id' => 158, 'name' => 'Spare System ass`y A', 'process_id' => '212'],
            ['id' => 159, 'name' => 'Spare Vacuum A', 'process_id' => '213'],
            ['id' => 160, 'name' => 'Spare Final A', 'process_id' => '214'],
            ['id' => 161, 'name' => 'Spare Packing A', 'process_id' => '215'],
            ['id' => 162, 'name' => 'Spare Door Bend A', 'process_id' => '216'],
            ['id' => 163, 'name' => 'Spare Door Foam A', 'process_id' => '217'],
            ['id' => 164, 'name' => 'Spare Inner Box B', 'process_id' => '218'],
            ['id' => 165, 'name' => 'Spare Roll B', 'process_id' => '219'],
            ['id' => 166, 'name' => 'Spare Cab pre-assy B', 'process_id' => '220'],
            ['id' => 167, 'name' => 'Spare PU Foam B', 'process_id' => '221'],
            ['id' => 168, 'name' => 'Spare Assembly B', 'process_id' => '222'],
            ['id' => 169, 'name' => 'Spare System ass`y B', 'process_id' => '223'],
            ['id' => 170, 'name' => 'Spare Vacuum B', 'process_id' => '224'],
            ['id' => 171, 'name' => 'Spare Final B', 'process_id' => '225'],
            ['id' => 172, 'name' => 'Spare Packing B', 'process_id' => '226'],
            ['id' => 173, 'name' => 'Spare Door Bend B', 'process_id' => '227'],
            ['id' => 174, 'name' => 'Spare Door Foam B', 'process_id' => '228'],
            ['id' => 175, 'name' => 'Spare PQC(A)', 'process_id' => '229'],
            ['id' => 176, 'name' => 'Spare PQC(B)', 'process_id' => '230'],
            ['id' => 177, 'name' => 'Spare Production ', 'process_id' => '231'],
            ['id' => 180, 'name' => 'Spare SAC', 'process_id' => '234'],
            ['id' => 181, 'name' => 'Spare WAC', 'process_id' => '235'],
            ['id' => 182, 'name' => 'PQC CAC', 'process_id' => '236'],
            ['id' => 184, 'name' => 'FG Warehouse (WAC)', 'process_id' => '238'],
            ['id' => 185, 'name' => 'RM Warehouse (WAC)', 'process_id' => '239'],
            ['id' => 186, 'name' => 'WAC PCB Assembly Line', 'process_id' => '240'],
            ['id' => 187, 'name' => 'Spare HR', 'process_id' => '241'],

        ];
        foreach ($departments as $key => $value) {
            Department::firstOrCreate($value);
        }
    }
}
