<?php

use App\Enum\KPIEnum;
use App\Models\KPI\Rule;
use App\Models\KPI\RuleCategory;
use Illuminate\Database\Seeder;

class RuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(Rule::class, 10)->create();
        $kpi = RuleCategory::where('name', 'kpi')->first()->id;
        $omg = RuleCategory::where('name', 'omg')->first()->id;
        $task = RuleCategory::where('name', 'key-task')->first()->id;
        // $sfd = [
        //     ['name' => 'Revenue', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Revenue-SAC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Revenue-WAC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Revenue-RF-Haier', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Revenue-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Revenue-RF', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Revenue-AC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'RM Margin', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Margin-SAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Margin-WAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Margin-RF-Haier', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Margin-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Margin-RF', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Margin-AC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'FG Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Delivery on time-RF-Haier', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Delivery on time-RF', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'WH (FG /RM )stock DIFF-AC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Efficiency of per Capita-SAC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Efficiency of per Capita-WAC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Efficiency of per Capita-RF-Haier', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Efficiency of per Capita-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'DIO', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'DIO-SAC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'DIO-RF-Haier', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'DIO-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Expenses (MFG+R&D)-SAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Expenses (MFG+R&D)-WAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Expenses (MFG+R&D)-RF-Haier', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Expenses (MFG+R&D)-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Production achieve plan-WAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Production stop line-WAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'RM Production stop line-Rf-Haier', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Production loss-WAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Production loss-RF-Haier', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Production loss-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'M/C Breakdown-AC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'M/C Breakdown-RF', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'New model launch on time-RF', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'FG Aging (FG 60+ inventory)ratio ≤3% (FG 180=0 )-RF', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'FG Aging (FG 60+ inventory)ratio ≤3% (FG 180=0 )-AC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Overdue', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Overdue-RF', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Overdue-AC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Sales Expense-RF', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Sales Expense-AC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'BOM Achievement', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'DIO RM', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Reject rate', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Department Expense Control-SCM', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Department Expense Control-FA', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Department Expense Control-UT', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Import Cost - RF/SAC/WAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Export Cost - RF/SAC/WAC', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Expense Control', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'CCC', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Aging Stock (30% Reduced from last year)', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'HR cost Efficiency', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Operating expenses', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Recruitment on time', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Staff efficiency', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'EMC timely Evaluation', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Risk Management', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Ontime Services and Quality Compliance', 'category_id' => $kpi, 'calculate_type' => 'Percent'],
        //     ['name' => 'Operations（Zero Break Down，Zero Problem)', 'category_id' => $kpi, 'calculate_type' => 'Amount'],
        //     ['name' => 'Energy Expense control', 'category_id' => $kpi, 'calculate_type' => 'Percent'],

        //     ['name' => 'B Class and Above Employees', 'category_id' => $omg],
        //     ['name' => 'SOP & Policies implementation', 'category_id' => $omg],
        //     ['name' => 'Report and Meeting Management', 'category_id' => $omg],
        //     ['name' => 'New Product', 'category_id' => $task],
        //     ['name' => 'Production loss improvement', 'category_id' => $task],
        //     ['name' => 'Efficiency improvement', 'category_id' => $task],
        //     ['name' => 'Inventory management', 'category_id' => $task],
        //     ['name' => 'FG aging clearing', 'category_id' => $task],
        //     ['name' => 'Quality improvement', 'category_id' => $task],
        //     ['name' => 'Warehouse management', 'category_id' => $task],
        //     ['name' => 'Production improvement', 'category_id' => $task],
        //     ['name' => 'Manpower management', 'category_id' => $task],
        //     ['name' => 'Purchasing management', 'category_id' => $task],
        //     ['name' => 'Equipment management', 'category_id' => $task],
        //     ['name' => 'Oder shipment', 'category_id' => $task],
        //     ['name' => 'Marketing Oder', 'category_id' => $task],
        //     ['name' => 'Accounts receivable', 'category_id' => $task],
        //     ['name' => 'Product develop', 'category_id' => $task],
        //     ['name' => 'Vender management', 'category_id' => $task],
        //     ['name' => 'Cost saving', 'category_id' => $task],
        //     ['name' => 'Cost management-WAC', 'category_id' => $task],
        //     ['name' => 'Cost management-T Door/G3', 'category_id' => $task],
        //     ['name' => 'Logistic management', 'category_id' => $task],
        //     ['name' => 'Budget Management', 'category_id' => $task],
        //     ['name' => 'Asset Management', 'category_id' => $task],
        //     ['name' => 'Cost Management', 'category_id' => $task],
        //     ['name' => 'Cash Management', 'category_id' => $task],
        //     ['name' => 'Accounting Management/Audit/TD', 'category_id' => $task],
        //     ['name' => 'Organization management', 'category_id' => $task],
        //     ['name' => 'Recruiting management', 'category_id' => $task],
        //     ['name' => 'Compensation and benefits management', 'category_id' => $task],
        //     ['name' => 'Manpower,Attendance- Overtime management', 'category_id' => $task],
        //     ['name' => 'Training management', 'category_id' => $task],
        //     ['name' => 'EHS management', 'category_id' => $task],
        //     ['name' => 'GA management', 'category_id' => $task],
        //     ['name' => '2021 Budget Activity management', 'category_id' => $task],
        //     ['name' => 'Report and Analysis management', 'category_id' => $task],
        //     ['name' => 'Meeting management', 'category_id' => $task],
        //     ['name' => 'Document management', 'category_id' => $task],
        //     ['name' => 'Legal management', 'category_id' => $task],
        //     ['name' => 'Project Closure management', 'category_id' => $task],
        //     ['name' => 'Inspection and Maintenance as per schedule', 'category_id' => $task],
        //     ['name' => 'Spare and Asset Management', 'category_id' => $task],
        //     ['name' => 'EHS & 6S improvement', 'category_id' => $task],

        // ];
        $rules =
            [
                ['name' => 'Revenue', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Revenue-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Revenue-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Revenue-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Revenue-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Revenue-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Revenue-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Margin', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Margin-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Margin-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Margin-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Margin-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Margin-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Margin-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'FG Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Delivery on time-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Delivery on time-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'WH (FG /RM )stock DIFF-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                ['name' => 'Efficiency of per Capita-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Efficiency of per Hour-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Efficiency of per Hour-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Efficiency of per Hour-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'DIO', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'DIO-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'DIO-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'DIO-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Expenses (MFG+R&D)-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Expenses (MFG+R&D)-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Expenses (MFG+R&D)-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Expenses (MFG+R&D)-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Production achieve plan-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RM Production stop line-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'RM Production stop line-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Production loss-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Production loss-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Production loss-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'M/C Breakdown-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'M/C Breakdown-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'New model launch on time-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'FG Aging (FG 60+ inventory)ratio ≤3% (FG 180=0 )-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'FG Aging (FG 60+ inventory)ratio ≤3% (FG 180=0 )-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Overdue', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                ['name' => 'Overdue-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                ['name' => 'Overdue-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                ['name' => 'Sales Expense-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Sales Expense-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'BOM Achievement', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'DIO RM', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Reject rate', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Department Expense Control-SCM', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Department Expense Control-FA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Department Expense Control-UT', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Import Cost - RF/SAC/WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Export Cost - RF/SAC/WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Expense Control', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'CCC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Aging Stock (30% Reduced from last year)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'HR cost Efficiency', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Operating expenses', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Recruitment on time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Staff efficiency', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'EMC timely Evaluation', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Risk Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Ontime Services and Quality Compliance', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Operations（Zero Break Down，Zero Problem)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                ['name' => 'Energy Expense control', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],


                ['name' => 'PD Plan Achieve Rate-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'FG leakage-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'FG sampling-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Going Straight Rate(FTR)-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Scrap Rate-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Efficiency of per Hour-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'MFG Expense-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'PD Plan Achieve Rate-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'FG leakage-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'FG sampling-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Going Straight Rate(FTR)-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Scrap Rate-WAC-PD', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'MFG Expense-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Scrap Rate-WAC-Inhouse', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'OEE-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Market Defect Rate-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Market Defect Rate-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'F-cost-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Incoming (fault detecting)-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Incoming (fault detecting)-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Closed customer claim on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'MFG Expense-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Customer claim', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                ['name' => 'OEE-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'New Product Development-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'PD Plan Achieve Rate-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Part reject rate-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'AGING RM over 90 days-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'New Model Launching on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Production on plan-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'MFG Expenses-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Going Straight Rate(FTR)-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Market Quality-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Delivery on time-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Production on plan-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'MFG Expenses-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Going Straight Rate(FTR)-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Market Quality-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Efficiency of per Hour-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Market Quality-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'New Model Launching market quality-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Quality Claim-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Part Reject from production line(fault delecting rate)-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'MFG Expenses-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'FG inspection-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Rework-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Delivery on time -RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Going Straight Rate(FTR)-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'LOB-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Project Innovation-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'DIO-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Inventory control-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Production on plan-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'New Model Launching on time-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Incoming Parts Pass-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'RM Production stop line-RF-Inhouse', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Production Loss-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'R&D Expenses-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Revenue-RF-Domestic&SA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Sales units-RF-Domestic&SA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Sales Expense-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Revenue-RF-Japan&Taiwan', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Sales units-RF-Japan&Taiwan', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Sales Expense-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Revenue-RF-SEA&USA&MEA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Sales units-RF-SEA&USA&MEA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'RF Margin-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Delivery on time-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Delivery on time-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Sales Units', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'FG Aging (FG 60+ inventory)ratio ≤ 3% (FG 180=0 )', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Overdue (Spare part)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                ['name' => 'Delivery on Time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Delivery on Time (Spare part)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Sales Expense-FOC spare part', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Negative Contribution Margin Models', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Forecast Accuracy', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'DPO', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Accuracy Bookeeping', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Audit Adjustment Amount', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Cash Flow Forecast Accuracy', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'PBC & Audit report', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Overdue', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                ['name' => 'DSO', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Exchange Rate Loss', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'BOM Cost Achievement', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Cost Saving (M THB)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'New products on time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'MOQ/LT', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Price corrective', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Import Customer clerance on time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Export customer clearance on time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'SOP Policy / Process / Regulation Update - GA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Asset Management-GA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Scrap management-GA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Facilities and Infrastructure (Canteen Management)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Events & Conferences management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'EHS Zero accident', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'SOP Policy / Process / Regulation Update - HTC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'ISO & Quality System Audit', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'SOP & ISO Document implement', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Effective Network', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'IT Asset Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Project Implementation as per plan', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'IT Expense Control', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                ['name' => 'Corporate Governance', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Compliance Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Contract Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Relationship Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'Litigation Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                ['name' => 'IP Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],


            ];

        foreach ($rules as $value) {
            Rule::firstOrCreate($value);
        }
    }
}
