<?php

use App\Enum\KPIEnum;
use App\Models\KPI\KpiRuleType;
use App\Models\KPI\Rule;
use App\Models\KPI\RuleCategory;
use App\Models\User;
use Illuminate\Database\Seeder;

class RuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(Rule::class, 10)->create();

        $rules = Rule::all();
        foreach ($rules as $key => $rule) {
            $rule_types = KpiRuleType::all()->random();
            $users = User::whereIn('username', ['70036084', '70037455', '70037539', '70037515'])->get()->random();
            $rule->kpi_rule_types_id = $rule_types->id;
            $rule->user_actual = $users->id;
            $rule->save();
        }
        /* 
            $kpi = RuleCategory::where('name', 'kpi')->first()->id;
            $omg = RuleCategory::where('name', 'omg')->first()->id;
            $task = RuleCategory::where('name', 'key-task')->first()->id;
            $rules =
                [
                    ['name' => 'Revenue', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Revenue-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Revenue-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Revenue-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Revenue-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Revenue-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Revenue-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Margin', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Margin-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Margin-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Margin-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Margin-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Margin-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Margin-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'FG Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Delivery on time-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Delivery on time-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Delivery on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'WH (FG /RM )stock DIFF-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                    ['name' => 'Efficiency of per Capita-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Efficiency of per Hour-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Efficiency of per Hour-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Efficiency of per Hour-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'DIO', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'DIO-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'DIO-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'DIO-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Expenses (MFG+R&D)-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Expenses (MFG+R&D)-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Expenses (MFG+R&D)-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Expenses (MFG+R&D)-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Production achieve plan-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM Production stop line-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'RM Production stop line-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Production loss-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Production loss-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Production loss-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'M/C Breakdown-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'M/C Breakdown-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'New model launch on time-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'FG Aging (FG 60+ inventory)ratio ≤3% (FG 180=0 )-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'FG Aging (FG 60+ inventory)ratio ≤3% (FG 180=0 )-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Overdue', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                    ['name' => 'Overdue-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                    ['name' => 'Overdue-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                    ['name' => 'Sales Expense-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Sales Expense-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'BOM Achievement', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'DIO RM', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Reject rate', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Department Expense Control-SCM', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Department Expense Control-FA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Department Expense Control-UT', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Import Cost - RF/SAC/WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Export Cost - RF/SAC/WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Expense Control', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'CCC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Aging Stock (30% Reduced from last year)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'HR cost Efficiency', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Operating expenses', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Recruitment on time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Staff efficiency', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'EMC timely Evaluation', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Risk Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Ontime Services and Quality Compliance', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Operations（Zero Break Down，Zero Problem)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                    ['name' => 'Energy Expense control', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],


                    ['name' => 'PD Plan Achieve Rate-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'FG leakage-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'FG sampling-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Going Straight Rate(FTR)-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Scrap Rate-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Efficiency of per Hour-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'MFG Expense-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'PD Plan Achieve Rate-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'FG leakage-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'FG sampling-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Going Straight Rate(FTR)-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Scrap Rate-WAC-PD', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'MFG Expense-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Scrap Rate-WAC-Inhouse', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'OEE-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Market Defect Rate-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Market Defect Rate-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'F-cost-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Incoming (fault detecting)-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Incoming (fault detecting)-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Closed customer claim on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'MFG Expense-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Customer claim', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                    ['name' => 'OEE-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Product Development-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'PD Plan Achieve Rate-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Part reject rate-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'AGING RM over 90 days-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Model Launching on time-AC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Production on plan-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'MFG Expenses-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Going Straight Rate(FTR)-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Market Quality-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Delivery on time-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Production on plan-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'MFG Expenses-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Going Straight Rate(FTR)-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Market Quality-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Efficiency of per Hour-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Market Quality-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'New Model Launching market quality-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Quality Claim-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Part Reject from production line(fault delecting rate)-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'MFG Expenses-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'FG inspection-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Rework-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Delivery on time -RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Going Straight Rate(FTR)-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'LOB-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Project Innovation-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'DIO-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Inventory control-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Production on plan-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Model Launching on time-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Incoming Parts Pass-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'RM Production stop line-RF-Inhouse', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Production Loss-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'R&D Expenses-RF', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Revenue-RF-Domestic&SA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sales units-RF-Domestic&SA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sales Expense-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Revenue-RF-Japan&Taiwan', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sales units-RF-Japan&Taiwan', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sales Expense-RF-AQUA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Revenue-RF-SEA&USA&MEA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sales units-RF-SEA&USA&MEA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RF Margin-RF-Haier', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Delivery on time-SAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Delivery on time-WAC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sales Units', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'FG Aging (FG 60+ inventory)ratio ≤ 3% (FG 180=0 )', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Overdue (Spare part)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                    ['name' => 'Delivery on Time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Delivery on Time (Spare part)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sales Expense-FOC spare part', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Negative Contribution Margin Models', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Forecast Accuracy', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'DPO', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Accuracy Bookeeping', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Audit Adjustment Amount', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cash Flow Forecast Accuracy', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'PBC & Audit report', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Overdue', 'category_id' => $kpi, 'calculate_type' => KPIEnum::zero_oriented_kpi],
                    ['name' => 'DSO', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Exchange Rate Loss', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'BOM Cost Achievement', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Saving (M THB)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New products on time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'MOQ/LT', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Price corrective', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Import Customer clerance on time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Export customer clearance on time', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'SOP Policy / Process / Regulation Update - GA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Asset Management-GA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Scrap management-GA', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Facilities and Infrastructure (Canteen Management)', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Events & Conferences management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'EHS Zero accident', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'SOP Policy / Process / Regulation Update - HTC', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'ISO & Quality System Audit', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'SOP & ISO Document implement', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Effective Network', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'IT Asset Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Project Implementation as per plan', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'IT Expense Control', 'category_id' => $kpi, 'calculate_type' => KPIEnum::negative],
                    ['name' => 'Corporate Governance', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Compliance Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Contract Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Relationship Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Litigation Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'IP Management', 'category_id' => $kpi, 'calculate_type' => KPIEnum::positive],

                    ['name' => 'New Product', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Production loss Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Efficiency Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Inventory Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'FG aging Clearing', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Quality Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Warehouse Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Production Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Manpower Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Purchasing Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Equipment Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Oder Shipment', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Marketing Oder', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Accounts Receivable', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Product Develop', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Vender Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Saving', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Management-WAC', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Management-T Door/G3', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Logistic Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Budget Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Asset Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cash Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Accounting Management/Audit/TD', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Organization Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Recruiting Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Compensation and benefits Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Manpower,Attendance- Overtime Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Training Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'EHS Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'GA Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => '2021 Budget Activity Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Report and Analysis Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Meeting Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Document Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Legal Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Project Closure Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Inspection and Maintenance as per schedule', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Spare and Asset Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'EHS & 6S Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'E&M Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Product (T-door)', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'IH Production Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Product Develop -T Door', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Aging clearance –Dead & Slow Moving Materials', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'BOM Cost Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Import & Export Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Indirect Procurement Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Planning Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Company Culture Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Operation Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RICA Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Innovation', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Quality Improvement Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Incoming Part Quality', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Outgoing Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Quality Control', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'BOM Accuracy', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'PP1 Sample Review', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'SAC New Model Development Problem', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Document Support of New Model', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Department Operating System Optimization', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Material T-1 All Set Complete', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Supplier Network Capability Check', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Mold Gap', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'OPSI Meeting and Complete', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Review Last Week Plan Achive and Analysis Gap', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Monitor Plan Execution', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Product Development', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Productivity Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'PD Stop time loss Reduce', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Innovation Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Reduce production Loss Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Reduce Production Loss', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Improvement Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Quality Standard Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Production Output Line (Unit/Hr)', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Quality Control Standard', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Process Quality Improvement Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'JIG&FIGTURE , MAKING ELECTOR', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'No Part Shortage', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Model Delivery on Time', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Aging Part Reduction', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Add Order', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Market Quality Improvement Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Reduce Aging Stock', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Down Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'BOM New Model Achived on Time', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Apply International Standard on Time', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Reduce Aging Stock (R&D FG) Clearing', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Maintenance and PM', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Aging Clear', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Order Managmenet', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Order Acquisition', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sale Contract Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Customer Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Cost Down', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Market Information', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Product Develop', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sample New Model', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Back Log Stock Clearing', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'GEA Monthly complete delivery', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Sales Forecast Accuracy', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'OTC Sales Ratio', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Product Development', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Complete FG aging weekly report', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Monthly key tasks complete', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'PSI management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Order Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'WAC Margin', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'T-Door Margin', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'CD Project Achievement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'RM 90+Inventory Ratio 6% (360 = 0)', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Price monitoring, part diff analysis and release monthly reports', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Update and/or Create SOP', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'FG Cost Monitoring and summart report release', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Delivery Commitment', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Quarter Ocean freight bidding', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Storage /Demurrage expense control and reduction', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Monthly report of logistic (IM/EX) expense : monitor/forecast/ analysis', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Logistic system online and upgrade', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'SBU Mgt. PL Rolling', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Project Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'HQD SOP Localization', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Team Development', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Reconciliation-All（Additional Reports）', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'On Time & Accurate Monthly Account Closing', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Taxation Compliance', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Payment Complain (Mistaken or Late pay)', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Credit Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'FX Hedging', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Scrap Control Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'GA Project Imporovement Control', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Expense Improvement Control', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Asset Management Project Improvement', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'First aid online', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Legal & other Requirements compliance for New Factory', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'New Certificate Project', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Safety System Protection', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Environment Control', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Task HQ & Local Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Service in Time', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Data Security', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Risk Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Department expense control', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'SOP & policies set up and implementation', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Document management and depository', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Contract Management', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Legal & Statutory Compliance', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Timely settlement of legal cases', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Relationship development', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Collaboration with HQ, RICA and other internal & external stakeholders', 'category_id' => $task, 'calculate_type' => KPIEnum::positive],

                    ['name' => 'B Class and Above Employees', 'category_id' => $omg, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'SOP & Policies implementation', 'category_id' => $omg, 'calculate_type' => KPIEnum::positive],
                    ['name' => 'Report and Meeting Management', 'category_id' => $omg, 'calculate_type' => KPIEnum::positive],
                ];

            foreach ($rules as $value) {
                Rule::firstOrCreate($value);
            }
        **/
    }
}
